variables:
  PROJECT_NAME: rbif-dashboard
  DOCKER_REGISTRY: 775597531690.dkr.ecr.us-east-1.amazonaws.com
  ORGANIZATION: rbif
  IMAGE_URL: $DOCKER_REGISTRY/$ORGANIZATION/$PROJECT_NAME

stages:
  - lint
  - build
  - deploy

.unstable_template: &unstable_template
  tags:
    - robo
  only:
    - unstable

.staging_template: &staging_template
  tags:
    - robo
  only:
    - staging

.production_template: &production_template
  tags:
    - robo
  only:
    - _master

.base_build_stage:
  stage: build
  script:
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker build -t $IMAGE_URL:$IMAGE_TAG -t $IMAGE_URL:$LATEST_TAG --build-arg="stage=$LATEST_TAG" --file=Dockerfile .
    - docker push $IMAGE_URL:$IMAGE_TAG
    - docker push $IMAGE_URL:$LATEST_TAG

    # remove old images version keep 2 version
    - docker images | egrep -e "$IMAGE_URL" | tail -n +3 | awk '{print $3}' | xargs -r docker rmi -f || echo 'Ignore'
  variables:
    IMAGE_TAG: staging.$CI_PIPELINE_ID
    LATEST_TAG: staging

.base_deploy_stage:
  stage: deploy
  script:
    - PYTHONUNBUFFERED=1 python3 /home/gitlab-runner/deploy_ecs.py $STAGE_NAME $SERVICE $IMAGE_URL:$IMAGE_TAG
  variables:
    IMAGE_TAG: staging.$CI_PIPELINE_ID
    STAGE_NAME: Robo-Staging
    SERVICE: RbifDashboard

# CI for unstable
# -------------------------------------------------------------------------------
build_unstable:
  <<: *unstable_template
  extends: .base_build_stage
  variables:
    IMAGE_TAG: unstable.$CI_PIPELINE_ID
    LATEST_TAG: unstable

deploy_unstable:
  <<: *unstable_template
  extends: .base_deploy_stage
  variables:
    IMAGE_TAG: unstable.$CI_PIPELINE_ID
    STAGE_NAME: Robo-Unstable
  environment:
    name: unstable
    url: https://dashboard-unstable.rbif.tech


# CI for staging
# -------------------------------------------------------------------------------
build_staging:
  <<: *staging_template
  extends: .base_build_stage
  variables:
    IMAGE_TAG: staging.$CI_PIPELINE_ID
    LATEST_TAG: staging

deploy_staging:
  <<: *staging_template
  extends: .base_deploy_stage
  variables:
    IMAGE_TAG: staging.$CI_PIPELINE_ID
    STAGE_NAME: Robo-Staging
  environment:
    name: staging
    url: https://dashboard-staging.rbif.tech
